### ISSUE TITLE
'lab_id', 'lab_name', 'exp_id', 'exp_name' are updated twice also old data is not deleted

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-industrial-automation-laboratory-coep#1]
'lab_id', 'lab_name', 'exp_id', 'exp_name' are updated twice also old data is not deleted

**Comment by sivashankerN** [comment]
Second exp_name and hosted Url was wrong for this lab. Checked with the LDS service. Asked @madhavipuliraju  about the changes to be made in the LDS database. 


Fixed the issue and @madhavipuliraju  updated the LDS database as well.
